"""the initial migration

Revision ID: 92194a32de6c
Revises: 
Create Date: 2019-05-14 07:54:52.891563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92194a32de6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
